name: My Mind
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25037
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffebb2'
    - '#aba64e'
    - '#d778a0'
    - '#492f22'
    - '#b64174'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
