name: My Mind
favicon: null
layout_spectrum: 0.3342626802623272
typography_spectrum: 0.7764345379546285
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.09281680546700954
  lightness: 0.4689202969893813
  saturation: 0.6143049062229693
  rhythmicContrast: 0.022716990439221263
purpose: []
